HanaLucky/kpter-web

kpter/db/migrate/20160821111222_create_t_cards.rb
kpter/db/schema.rb

t_cardsテーブルに「担当者」のカラムを追加

---

kpter/spec/models/user_spec.rb

Fixes #45.
UserモデルのRSpec（describeとit）を実装。

add describe to user rspec

---

kpter/app/models/board.rb
kpter/app/models/community.rb
kpter/app/models/kp_card.rb
kpter/app/models/t_card.rb
kpter/app/models/user.rb
kpter/db/migrate/20160821102917_create_communities.rb
kpter/db/migrate/20160821103017_create_boards.rb
kpter/db/migrate/20160821111045_create_community_users.rb
kpter/db/migrate/20160821111135_create_kp_cards.rb
kpter/db/migrate/20160821111222_create_t_cards.rb
kpter/db/migrate/20160821111234_create_memos.rb
kpter/db/schema.rb

Fixes #39 
テーブル定義に従ってマイグレートファイルを修正 => [テーブル定義](https://docs.google.com/spreadsheets/d/1IS4yLM9SRq7O8YsxSzHEujOHsjEwjFuYOdz5jTpfFq8/edit?usp=sharing)
usersテーブルはdeviseで生成されたままの状態を利用したい理由で修正しませんでした。

migrateファイル作成

---

kpter/spec/models/user_spec.rb

User RSpecに検査項目を追加しました

---

kpter/db/migrate/20160821111045_create_community_users.rb
kpter/db/schema.rb
kpter/spec/models/community_spec.rb

communityのspec記述

---

kpter/Gemfile
kpter/Gemfile.lock
kpter/config/environments/test.rb
kpter/spec/factories/users.rb
kpter/spec/rails_helper.rb

userのcreateがSpecで動作するように修正

---

kpter/app/models/community_user.rb
kpter/app/models/user.rb
kpter/config/locales/en.yml
kpter/config/locales/ja.yml
kpter/spec/models/user_spec.rb

implemented user model

---

kpter/config/routes.rb

Fixes #75 
```
$ bundle exec rake routes
Prefix Verb   URI Pattern                                          Controller#Action
new_user_session GET    /users/sign_in(.:format)                             devise/sessions#new
user_session POST   /users/sign_in(.:format)                             devise/sessions#create
destroy_user_session DELETE /users/sign_out(.:format)                            devise/sessions#destroy
user_password POST   /users/password(.:format)                            devise/passwords#create
new_user_password GET    /users/password/new(.:format)                        devise/passwords#new
edit_user_password GET    /users/password/edit(.:format)                       devise/passwords#edit
PATCH  /users/password(.:format) …
```

mypage, community, board画面のroutes実装

---

kpter/config/environments/development.rb
kpter/config/routes.rb

- マイページのルーティング修正
- mailerの設定修正

fix routing & mailer setting

---

kpter/config/environments/development.rb

fix mailer setting

---

kpter/app/views/welcome/index.html.erb

開発用のサインアップ／ログイン導線を実装

---

kpter/config/environments/development.rb

branchは消さないでおいていただけるとありがたいです！
こんな感じでみれるようになる。

mailcatcherのメーラーでユーザー認証メールがみれるように修正

---

kpter/app/assets/javascripts/mypages.coffee
kpter/app/assets/stylesheets/mypages.scss
kpter/app/controllers/mypages_controller.rb
kpter/app/helpers/mypages_helper.rb
kpter/app/views/mypages/show.html.erb
kpter/spec/controllers/mypages_controller_spec.rb
kpter/spec/helpers/mypages_helper_spec.rb
kpter/spec/views/mypages/show.html.erb_spec.rb

create mypage & community/task count

---

kpter/app/assets/javascripts/communities.coffee
kpter/app/assets/stylesheets/communities.scss
kpter/app/controllers/communities_controller.rb
kpter/app/helpers/communities_helper.rb
kpter/app/views/communities/show.html.erb
kpter/spec/controllers/communities_controller_spec.rb
kpter/spec/helpers/communities_helper_spec.rb
kpter/spec/views/communities/show.html.erb_spec.rb

コミュニティ画面にボード数の表示を実装

---

kpter/app/views/mypages/show.html.erb

implemented community list view

---

kpter/app/assets/javascripts/application.js
kpter/vendor/assets/javascripts/dataTables/dataTables.responsive.js

dataTables.responsive.jsの追加

---

kpter/Gemfile
kpter/Gemfile.lock
kpter/app/views/kaminari/_first_page.html.erb
kpter/app/views/kaminari/_gap.html.erb
kpter/app/views/kaminari/_last_page.html.erb
kpter/app/views/kaminari/_next_page.html.erb
kpter/app/views/kaminari/_page.html.erb
kpter/app/views/kaminari/_paginator.html.erb
kpter/app/views/kaminari/_prev_page.html.erb
kpter/config/initializers/kaminari_config.rb

add kaminari

---

kpter/Gemfile
kpter/Gemfile.lock
kpter/app/assets/javascripts/communities.coffee
kpter/app/assets/javascripts/communities/show.js
kpter/app/controllers/communities_controller.rb
kpter/app/controllers/mypages_controller.rb
kpter/app/views/communities/_boards.html.erb
kpter/app/views/communities/show.html.erb
kpter/app/views/communities/show.js.erb
kpter/app/views/kaminari/_first_page.html.erb
kpter/app/views/kaminari/_gap.html.erb
kpter/app/views/kaminari/_last_page.html.erb
kpter/app/views/kaminari/_next_page.html.erb
kpter/app/views/kaminari/_page.html.erb
kpter/app/views/kaminari/_paginator.html.erb
kpter/app/views/kaminari/_prev_page.html.erb
kpter/app/views/mypages/_tasks.html.erb
kpter/app/views/mypages/show.html.erb
kpter/config/application.rb
kpter/config/environments/production.rb
kpter/config/initializers/assets.rb
kpter/config/initializers/kaminari_config.rb
kpter/config/initializers/time_formats.rb
kpter/config/locales/en.yml
kpter/config/locales/ja.yml
kpter/config/routes.rb

Fixes #86 
git mergeで@hanaori さんのコミット混じって差分がめちゃくちゃになってしまい、申し訳ないです。もうやだこれ。

コミュニティページ | ボード一覧表示追加

---

kpter/Gemfile
kpter/Gemfile.lock
kpter/app/assets/javascripts/application.js
kpter/app/assets/javascripts/communities/show.js
kpter/app/assets/stylesheets/application.css
kpter/app/assets/stylesheets/communities.scss
kpter/app/controllers/communities_controller.rb
kpter/app/views/communities/_side_column.html.erb
kpter/app/views/communities/show.html.erb
kpter/config/initializers/assets.rb

コミュニティ名のその場編集実装

---

kpter/app/views/welcome/_header.html.erb
kpter/app/views/welcome/index.html.erb
kpter/config/initializers/devise.rb

LPのヘッダーにログイン導線を追加

---

kpter/app/assets/stylesheets/style.css
kpter/app/views/application/_header.html.erb
kpter/app/views/communities/_side_column.html.erb
kpter/app/views/communities/show.html.erb
kpter/app/views/layouts/application.html.erb
kpter/app/views/mypages/_side_column.html.erb
kpter/app/views/mypages/show.html.erb
kpter/app/views/welcome/_header.html.erb

LP後のheader作成

---

kpter/app/assets/javascripts/application.js
kpter/app/assets/javascripts/common.js
kpter/app/assets/javascripts/communities/show.js
kpter/app/views/communities/show.html.erb

Edit In Place復活

---

kpter/app/controllers/application_controller.rb

redirect to mypage after signin

---

kpter/app/views/application/_header.html.erb
kpter/app/views/welcome/_header.html.erb
kpter/app/views/welcome/index.html.erb

remove unwanted elements

---

kpter/app/views/communities/show.html.erb
kpter/app/views/mypages/show.html.erb

データがない場合の表示追加

---

kpter/app/models/community.rb
kpter/app/models/t_card.rb
kpter/app/models/tcard_assignee.rb
kpter/app/models/user.rb
kpter/db/migrate/20160821111222_create_t_cards.rb
kpter/db/migrate/20161127051758_create_tcard_assignees.rb
kpter/db/schema.rb
kpter/spec/factories/tcard_assignees.rb
kpter/spec/models/community_spec.rb
kpter/spec/models/tcard_assignee_spec.rb
kpter/spec/models/user_spec.rb

Fixes #150.
- TcardAssigneeモデルの追加
- Userモデルの修正
- Communityモデルの修正

add TcardAssignee model

---

kpter/app/models/community.rb
kpter/app/models/user.rb
kpter/app/views/application/_tasks.html.erb
kpter/app/views/communities/refresh_tasks.js.erb
kpter/app/views/communities/show.html.erb
kpter/app/views/mypages/refresh_tasks.js.erb
kpter/app/views/mypages/show.html.erb
kpter/db/schema.rb

タスク一覧に担当者を追加

---

kpter/Gemfile
kpter/Gemfile.lock
kpter/app/assets/javascripts/application.js
kpter/app/assets/javascripts/components.js
kpter/config/environments/development.rb
kpter/config/environments/production.rb

Fixes #156 
こちらを参考にしました。
https://github.com/reactjs/react-rails

add react-rails

---

kpter/Gemfile
kpter/Gemfile.lock
kpter/app/assets/javascripts/application.js
kpter/app/assets/javascripts/components.js
kpter/config/environments/development.rb
kpter/config/environments/production.rb

This reverts commit f075a1912fd360c8d6c23e7c0f4fd1e6b1f34cb0.
Fixes #156

Revert "add react-rails"

---

kpter/app/controllers/application_controller.rb
kpter/app/controllers/boards_controller.rb
kpter/app/controllers/communities_controller.rb
kpter/app/controllers/mypages_controller.rb

ログインチェックフィルター追加

---

kpter/app/assets/stylesheets/bootstrap.css.map
kpter/app/assets/stylesheets/welcome/bootstrap/css/bootstrap.min.css.map
kpter/config/environments/development.rb

不要なログを出力しないように修正

---

kpter/app/controllers/application_controller.rb
kpter/app/models/user.rb
kpter/app/views/devise/mailer/confirmation_instructions.html.erb
kpter/app/views/devise/mailer/password_change.html.erb
kpter/app/views/devise/mailer/reset_password_instructions.html.erb
kpter/app/views/devise/mailer/unlock_instructions.html.erb
kpter/app/views/devise/registrations/new.html.erb
kpter/db/migrate/20160821105424_devise_create_users.rb
kpter/db/schema.rb

ユーザー登録画面でユーザー名を登録できるようにする #173

---

kpter/Gemfile
kpter/Gemfile.lock
kpter/config/environments/development.rb
kpter/config/routes.rb

開発環境で簡単にメールが確認できるようにする。
`http://{{domain}}/letter_opener` でメールが確認できる。

add letter_opener_web

---

kpter/app/models/user.rb

fixed #182 an error occurre when task was closed on MyPage

---

kpter/app/assets/stylesheets/application.css
kpter/app/assets/stylesheets/debugger.scss
kpter/app/views/layouts/application.html.erb
kpter/config/initializers/assets.rb

display debbug information

---

kpter/app/helpers/application_helper.rb

neglect-of-test

---

kpter/app/assets/javascripts/boards/card.js
kpter/app/assets/javascripts/channels/board.coffee
kpter/app/channels/board_channel.rb
kpter/app/controllers/boards_controller.rb
kpter/app/jobs/application_job.rb
kpter/app/jobs/card_broadcast_job.rb
kpter/app/models/kp_card.rb
kpter/app/models/t_card.rb
kpter/app/views/boards/show.html.erb
kpter/app/views/cards/_kpcard.html.erb
kpter/app/views/cards/_tcard.html.erb
kpter/spec/jobs/card_broadcast_job_spec.rb

ボード画面（カード初期保存）

---

kpter/.gitignore

redisのダンプファイルをgitignore

---

kpter/app/assets/javascripts/boards/cards.coffee
kpter/app/assets/javascripts/channels/board.coffee
kpter/app/assets/stylesheets/boards/style.css
kpter/app/views/boards/show.html.erb
kpter/app/views/cards/_kpcard.html.erb
kpter/app/views/layouts/board_layout.html.erb

Fixes #217
ボードのデザインをmaterial designに変更。
色は後から調整。

change card design

---

app/assets/javascripts/boards/card.js
app/assets/javascripts/boards/cards.coffee
app/assets/javascripts/channels/board.coffee
app/assets/stylesheets/boards/style.css
app/views/boards/show.html.erb
app/views/cards/_kpcard.html.erb
app/views/cards/_tcard.html.erb

change card and button design

---

app/assets/javascripts/boards/card.js
app/assets/javascripts/boards/cards.coffee
app/assets/javascripts/channels/board.coffee
app/assets/stylesheets/boards/style.css
app/assets/stylesheets/style.scss
app/views/cards/_kpcard.html.erb
app/views/cards/_tcard.html.erb

renew delete card design

---

Gemfile
Gemfile.lock

add debug gems

---

app/assets/javascripts/boards/cards.coffee
app/assets/javascripts/channels/board.coffee
app/channels/board_channel.rb
app/jobs/set_deadline_broadcast_job.rb
app/views/cards/_tcard.html.erb
spec/jobs/set_deadline_broadcast_job_spec.rb

set deadline

---

app/views/layouts/board_layout.html.erb

add sources

---

app/assets/stylesheets/welcome/welcome.scss
app/controllers/privacy_controller.rb
app/controllers/terms_controller.rb
app/views/devise/registrations/new.html.erb
app/views/layouts/welcome_layout.html.erb
app/views/privacy/show.html.erb
app/views/terms/show.html.erb
app/views/welcome/index.html.erb
config/routes.rb

- 規約ページ作成
- 問い合わせページ作成
- 利用規約ページ作成

#242 implement top page

---

app/assets/javascripts/common.js
app/assets/javascripts/communities.js
app/assets/javascripts/mypages.js
app/assets/stylesheets/style.scss
app/controllers/communities_controller.rb
app/controllers/t_cards_controller.rb
app/models/t_card.rb
app/views/communities/_edit.html.erb
app/views/communities/_joining.html.erb
app/views/communities/joining.js.erb
app/views/communities/refresh_tasks.js.erb
app/views/communities/show.js.erb
app/views/layouts/application.html.erb
app/views/mypages/refresh_tasks.js.erb
app/views/mypages/show.html.erb
app/views/t_cards/_modal_edit.html.erb
app/views/t_cards/_modal_edit.js.erb
app/views/t_cards/_t_card.html.erb
app/views/t_cards/_t_card.js.erb
app/views/t_cards/_t_card_table.html.erb
config/locales/en.yml
config/routes.rb

adding function to edit t_card

---

app/assets/javascripts/channels/board.coffee

fix deleting tcard

---

app/assets/javascripts/channels/board.coffee
app/assets/stylesheets/boards/style.css

user-modifyは消え行くらしい...
https://docs.google.com/document/d/1HlI8j-tJAG2sB0o2e7Xl4qCc0UC0mrOCk9UVO2leC1g/edit#heading=h.hrdkozsddouf
ので対応する。

hello textarea

---

app/assets/stylesheets/boards/style.css

textarea without line

---

app/assets/javascripts/channels/board.coffee
app/assets/stylesheets/boards/style.css
app/channels/board_channel.rb
app/controllers/boards_controller.rb
app/jobs/assign_broadcast_job.rb
app/views/boards/_members.html.erb
app/views/layouts/board_layout.html.erb
app/views/t_cards/_t_card.html.erb
spec/jobs/assign_broadcast_job_spec.rb

assign on board

---

Gemfile
Gemfile.lock
app/assets/images/google-logo.svg
app/assets/stylesheets/style.scss
app/assets/stylesheets/users/edit.scss
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/registrations_controller.rb
app/models/social_profile.rb
app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
config/initializers/devise.rb
config/initializers/omniauth.rb
config/initializers/session_store.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20180315125556_create_social_profiles.rb
db/migrate/20180319131711_remove_uid_provider_from_users.rb
db/migrate/20180321043855_add_only_o_auth_registration_to_users.rb
db/schema.rb
spec/factories/social_profiles.rb
spec/models/social_profile_spec.rb

resolved #272 sign up with google account

---

app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/registrations_controller.rb
config/locales/devise.en.yml
config/locales/en.yml

ソーシャルアカウントの重複登録を禁止

---

app/assets/javascripts/channels/board.coffee
app/views/boards/_members.html.erb

color button when selected

---

app/assets/javascripts/channels/board.coffee
app/assets/stylesheets/boards/style.css
app/views/boards/show.html.erb
app/views/layouts/board_layout.html.erb

tweak board

---

app/assets/stylesheets/boards/style.css
app/views/boards/show.html.erb

back to community

---

app/assets/stylesheets/boards/style.css
app/channels/board_channel.rb
app/models/t_card.rb

Issue160 tweak board

---

Gemfile
Gemfile.lock
app/controllers/users/registrations_controller.rb
app/helpers/application_helper.rb
app/models/user.rb
config/application.rb
config/settings.yml

upload gcs

---

config/environments/production.rb
config/initializers/devise.rb

add setting send mail

---

config/environments/production.rb

ENVはダブルクォーテーションでくくってはいけない

---

app/models/user.rb
config/settings.yml

Gloud Storageの認証はサービスアカウントに任せる

---

config/initializers/devise.rb

環境変数名を明確にした

---

Gemfile
Gemfile.lock
bin/bundle
bin/rails
bin/update
bin/yarn
config/application.rb
config/boot.rb
config/cable.yml
config/environment.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/application_controller_renderer.rb
config/initializers/assets.rb
config/initializers/content_security_policy.rb
config/initializers/cookies_serializer.rb
config/initializers/new_framework_defaults_5_2.rb
config/initializers/wrap_parameters.rb
config/locales/en.yml
config/puma.rb
config/routes.rb
config/spring.rb
config/storage.yml

upgrade to rails 5.2

---

app/models/user.rb
db/schema.rb

ファイル名をマルチバイトでなくエンコードしてしまう

---

app/controllers/users/omniauth_callbacks_controller.rb
config/environments/development.rb

ソーシャルログインでユーザー登録した場合にConfirmation mailを送信しない

---

app/views/devise/passwords/edit.html.erb

パスワード変更画面をマテリアルデザインに修正

---

Dockerfile
config/puma.rb

fix docker

---

app/controllers/application_controller.rb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/layouts/email.html.erb
config/initializers/devise.rb
config/locales/devise.en.yml
config/locales/devise.ja.yml

メールのローカライズ対応

---

config/cable.yml
config/environments/production.rb

fix action cable setting

---

app/assets/javascripts/channels/board.coffee

fix assign

---

docker-compose.yml

remove redis from docker-compose

---

Dockerfile

fix project name

---

config/environments/production.rb

add stg origin to allowed request origin setting

---

app/controllers/application_controller.rb

xxx_urlのプロトコル部分がhttpて

---

app/assets/javascripts/channels/board.coffee

fix board like bug
